name: Pruebas unitarias
on:
  push:
    branches: [ master ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Verificar versión de Python
      run: python --version
    - name: Checkout de repositorio
      uses: actions/checkout@v3
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4
      with:
          python-version: '3.12'
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py